CREATE TABLE IF NOT EXISTS `LA_USER` (
  `LA_USER_IDX` bigint(20) unsigned NOT NULL auto_increment,
  `LA_USER_TOKEN` varchar(200) NOT NULL,
  `LA_USER_NAME` varchar(20) NOT NULL,
  `LA_USER_ID` varchar(20) NOT NULL,
  `LA_USER_PW` varchar(40) NOT NULL,
  `LA_USER_EMAIL` text NOT NULL,
  `LA_USER_SEX` boolean DEFAULT 0,
  `LA_USER_AGE` int(2) NOT NULL,
  `LA_USER_PHONE` varchar(11) NOT NULL,
  `LA_USER_EXP` text NOT NULL,
  `LA_USER_PROFILE` text NOT NULL,
  `LA_USER_JOIN_DATE` varchar(10) NOT NULL,
  PRIMARY KEY  (`LA_USER_IDX`),
  UNIQUE KEY (`LA_USER_TOKEN`)
) ENGINE = MyISAM DEFAULT CHARSET = utf8 AUTO_INCREMENT = 1;

//

CREATE TABLE IF NOT EXISTS `LA_GAME` (
  `LA_GAME_IDX` bigint(20) unsigned NOT NULL auto_increment,
  `LA_GAME_TOKEN` varchar(200) NOT NULL,
  `LA_GAME_NAME` varchar(20) NOT NULL,
  `LA_GAME_COMPANY` varchar(20) NOT NULL,
  `LA_GAME_PACKAGE` varchar(40) NOT NULL,
  `LA_GAME_STAGE` int(1) NOT NULL,
  `LA_GAME_USERS` text NOT NULL,
  `LA_GAME_RIDERSHIP` int(8) NOT NULL,
  `LA_GAME_GRADE` text NOT NULL,
  PRIMARY KEY  (`LA_GAME_IDX`)
) ENGINE = MyISAM DEFAULT CHARSET = utf8 AUTO_INCREMENT = 1;

//

CREATE TABLE IF NOT EXISTS `LA_DEV_USER` (
  `LA_DEV_IDX` bigint(20) unsigned NOT NULL auto_increment,
  `LA_DEV_ID` varchar(20) NOT NULL,
  `LA_DEV_PW` varchar(40) NOT NULL,
  `LA_DEV_PHONE` varchar(11) NOT NULL,
  `LA_DEV_EMAIL` varchar(30) NOT NULL,
  `LA_DEV_GAME` text NOT NULL,
  PRIMARY KEY  (`LA_DEV_IDX`)
) ENGINE = MyISAM DEFAULT CHARSET = utf8 AUTO_INCREMENT = 1;


CREATE TABLE IF NOT EXISTS `LA_USER_GAMES` (
  `LA_USER_TOKEN` varchar(200) NOT NULL,
  `LA_GAME_TOKEN` text DEFAULT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS `LA_USER_ACHIEVEMENT` (
  `LA_USER_TOKEN` varchar(200) NOT NULL,
  `LA_ACHIEVEMENT` text DEFAULT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS `LA_USER_FOLLOWER` (
  `LA_USER_TOKEN_0` varchar(200) NOT NULL,
  `LA_USER_TOKEN_1` varchar(200) NOT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 AUTO_INCREMENT = 1;

//
//
//

CREATE TABLE IF NOT EXISTS `PB_ROOM` (
  `PB_ROOM_IDX` bigint(20) unsigned NOT NULL auto_increment,
  `PB_ROOM_TOKEN` varchar(200) NOT NULL,
  `PB_ROOM_NAME` varchar(20) NOT NULL,
  `PB_ROOM_MNG` varchar(200) NOT NULL,
  `PB_ROOM_AGE` int(3) NOT NULL,
  `PB_ROOM_PROFILE` text NOT NULL,
  `PB_ROOM_REG_DATE` datetime NOT NULL,
  `PB_ROOM_MEM_LIMIT` int NOT NULL,
  `PB_ROOM_TAG_0` text NOT NULL,
  `PB_ROOM_TAG_1` text NOT NULL,
  `PB_ROOM_TAG_2` text NOT NULL,
  `PB_ROOM_TAG_3` text NOT NULL,
  `PB_ROOM_TAG_4` text NOT NULL,
  PRIMARY KEY  (`PB_ROOM_IDX`)
) ENGINE = MyISAM DEFAULT CHARSET = utf8 AUTO_INCREMENT = 1;

//

CREATE TABLE IF NOT EXISTS `PB_BBS` (
  `PB_BBS_IDX` bigint(20) unsigned NOT NULL auto_increment,
  `PB_ROOM_IDX` bigint(20),
  `PB_BBS_CONTENT` text NOT NULL,
  `PB_BBS_WRITER` varchar(200) NOT NULL,
  `PB_BBS_REG_DATE` datetime NOT NULL,
  PRIMARY KEY  (`PB_BBS_IDX`)
) ENGINE = MyISAM DEFAULT CHARSET = utf8 AUTO_INCREMENT = 1;

//

CREATE TABLE IF NOT EXISTS `PB_COMMENT` (
  `PB_BBS_IDX` text NOT NULL,
  `PB_COMMENT_WRITER` varchar(200) NOT NULL,
  `PB_COMMENT_CONTENT` text NOT NULL,
  `PB_COMMENT_REG_DATE` datetime NOT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 AUTO_INCREMENT = 1;
