CREATE TABLE IF NOT EXISTS `LA_USER` (
  `LA_USER_TOKEN` varchar(200) NOT NULL,
  `LA_USER_NAME` varchar(20) NOT NULL,
  `LA_USER_ID` varchar(20) NOT NULL,
  `LA_USER_PW` varchar(40) NOT NULL,
  `LA_USER_EMAIL` text NOT NULL,
  `LA_USER_SEX` boolean DEFAULT 0,
  `LA_USER_AGE` int(2) NOT NULL,
  `LA_USER_PHONE` varchar(11) NOT NULL,
  `LA_USER_EXP` int(10) DEFAULT 0,
  `LA_USER_PROFILE` text NOT NULL,
  `LA_USER_JOIN_DATE` datetime NOT NULL,
  UNIQUE KEY (`LA_USER_TOKEN`)
) ENGINE = MyISAM DEFAULT CHARSET = utf8 AUTO_INCREMENT = 1;



CREATE TABLE IF NOT EXISTS `LA_GAME` (
  `LA_GAME_TOKEN` varchar(200) NOT NULL,
  `LA_GAME_NAME` varchar(20) NOT NULL,
  `LA_GAME_COMPANY` varchar(20) NOT NULL,
  `LA_GAME_PACKAGE` varchar(40) NOT NULL,
  `LA_GAME_STAGE` int(1) NOT NULL,
  `LA_GAME_USERS` text NOT NULL,
  `LA_GAME_RIDERSHIP` int(8) NOT NULL,
  `LA_GAME_GRADE` text NOT NULL,
  UNIQUE KEY  (`LA_GAME_TOKEN`)
) ENGINE = MyISAM DEFAULT CHARSET = utf8 AUTO_INCREMENT = 1;



CREATE TABLE IF NOT EXISTS `LA_DEV_USER` (
  `LA_DEV_ID` varchar(20) NOT NULL,
  `LA_DEV_PW` varchar(40) NOT NULL,
  `LA_DEV_PHONE` varchar(11) NOT NULL,
  `LA_DEV_EMAIL` varchar(30) NOT NULL,
  `LA_DEV_GAME` text NOT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 AUTO_INCREMENT = 1;



CREATE TABLE IF NOT EXISTS `LA_USER_GAMES` (
  `LA_USER_TOKEN` varchar(200) NOT NULL,
  `LA_GAME_TOKEN` varchar(200) DEFAULT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 AUTO_INCREMENT = 1;



CREATE TABLE IF NOT EXISTS `LA_USER_ACHIEVEMENT` (
  `LA_USER_TOKEN` varchar(200) NOT NULL,
  `LA_ACHIEVEMENT` text DEFAULT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 AUTO_INCREMENT = 1;



CREATE TABLE IF NOT EXISTS `LA_USER_FOLLOWER` (
  `LA_USER_TOKEN_0` varchar(200) NOT NULL,
  `LA_USER_TOKEN_1` varchar(200) NOT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 AUTO_INCREMENT = 1;



CREATE TABLE IF NOT EXISTS `LA_USER_QUEUE` (
  `LA_DEV_PHONE` varchar(11) NOT NULL,
  `LA_DEV_EMAIL` varchar(30) NOT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 AUTO_INCREMENT = 1;



CREATE TABLE IF NOT EXISTS `PB_ROOM` (
  `PB_ROOM_TOKEN` varchar(200) NOT NULL,
  `PB_ROOM_NAME` varchar(20) NOT NULL,
  `PB_ROOM_MNG` varchar(200) NOT NULL,
  `PB_ROOM_MIN_AGE` int(3) NOT NULL,
  `PB_ROOM_MAX_AGE` int(3) NOT NULL,
  `PB_ROOM_PROFILE` text NOT NULL,
  `PB_ROOM_REG_DATE` datetime NOT NULL,
  `PB_ROOM_MEM_LIMIT` int NOT NULL,
  `PB_ROOM_MEM_COUNT` int DEFAULT 1,
  `PB_ROOM_IS_PRIVATE` boolean DEFAULT 0,
  `PB_ROOM_TAG_0` text NOT NULL,
  `PB_ROOM_TAG_1` text NOT NULL,
  `PB_ROOM_TAG_2` text NOT NULL,
  `PB_ROOM_TAG_3` text NOT NULL,
  `PB_ROOM_TAG_4` text NOT NULL,
  `PB_ROOM_GREETING` text NOT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 AUTO_INCREMENT = 1;



CREATE TABLE IF NOT EXISTS `PB_USER_ROOM` (
  `LA_USER_TOKEN` varchar(200),
  `PB_ROOM_TOKEN` varchar(200),
  `USER_RANK` int(1) DEFAULT 0
) ENGINE = MyISAM DEFAULT CHARSET = utf8 AUTO_INCREMENT = 1;



CREATE TABLE IF NOT EXISTS `PB_BBS` (
  `PB_BBS_IDX` bigint(20) unsigned NOT NULL auto_increment,
  `PB_ROOM_TOKEN` varchar(200),
  `PB_BBS_CONTENT` text NOT NULL,
  `LA_USER_TOKEN` varchar(200) NOT NULL,
  `PB_BBS_REG_DATE` datetime NOT NULL,
  PRIMARY KEY  (`PB_BBS_IDX`)
) ENGINE = MyISAM DEFAULT CHARSET = utf8 AUTO_INCREMENT = 1;



CREATE TABLE IF NOT EXISTS `PB_COMMENT` (
  `PB_COMMENT_IDX` bigint(20) unsigned NOT NULL auto_increment,
  `PB_BBS_IDX` text NOT NULL,
  `LA_USER_TOKEN` varchar(200) NOT NULL,
  `PB_COMMENT_CONTENT` text NOT NULL,
  `PB_COMMENT_REG_DATE` datetime NOT NULL,
  PRIMARY KEY  (`PB_COMMENT_IDX`)
) ENGINE = MyISAM DEFAULT CHARSET = utf8 AUTO_INCREMENT = 1;
